function compute_bifurcations_2D()
% 
% This function computes several sections of the 
% phase portrait generated by the system 
%
% dx/dt = f1(x,y,mu) 
% dy/dt = f2(x,y,mu)
%
% as a function of the parameter mu 
%
%  
%       f1,f2 -> function handles in the form f(x,y,mu)
%           A -> two dimensional vector A=[ax,ay] 
%           B -> two dimensional vector B=[bx,by]
%                (see below)
%                         --------- B=(bx, by)
%                        |         |
%                        |         |
%                         ---------
%                   A=(ax,ay)
%
%          mu -> two dimensional vector mu=[mu1,mu2]
%                (range of the bifurcation parameter)
%

% example from the book (subcritical pitchfork)

% Saddle node bifurcation at mu=-1
% f1=@(x,y,mu) y-2*x;
% f2=@(x,y,mu) -mu+x.^2-y;
% mu = [-1.5, -.5];
% A  = [-2,-2];
% B  = [4,4];


% Hopf bifurcation at mu=0 
f1=@(x,y,mu) -y +mu*x+x.*y;
f2=@(x,y,mu) x+mu*y-x^2;
mu = [-1, 1];
A  = [-2,-2];
B  = [2,2];



Nmu=9;
MU = linspace(mu(1),mu(2),Nmu);

figure(1)
clf
for ii=1:length(MU)
  plot_phase_plane(f1,f2, MU(ii), A(1), A(2), B(1), B(2),ii)
end













function  plot_phase_plane(f1, f2, mu, ax, ay, bx, by,I)



% We use X,Y for computing the nullclines and the trajectories
Nx=200; 
Ny=200;
xx=linspace(ax,bx,Nx);
yy=linspace(ay,by,Ny);
[X,Y]=meshgrid(xx,yy);

fontsize=10;


subplot(3,3,I);
hold

%box on
%leg=legend('$\dot{x}=0$','$\dot{y}=0$')

% Here we sample the initial condition for the trajectories 
p  = haltonset(2,'Skip',1e3,'Leap',1e2);
p  = scramble(p,'RR2');
X0 = net(p,200);
X0(:,1)= ax + (bx-ax)*X0(:,1);
X0(:,2)= ay + (by-ay)*X0(:,2);

streamline(X,Y,f1(X,Y,mu),f2(X,Y,mu),X0(:,1),X0(:,2),[5e-3,1e4])


%set(leg,'Interpreter','Latex')
xlabel('$x$','Interpreter','Latex','Fontsize',fontsize)
ylabel('$y$','Interpreter','Latex','Fontsize',fontsize)
set(gca,'Fontsize',fontsize)
axis tight

% Here we plot the velocity field 
Nx1=20; 
Ny1=20;
xx1=linspace(ax,bx,Nx1);
yy1=linspace(ay,by,Ny1);
[X1,Y1]=meshgrid(xx1,yy1);
quiver(X1,Y1,f1(X1,Y1,mu),f2(X1,Y1,mu),'m','Linewidth',1.2)

[C1,h1]=contour(X,Y,f1(X,Y,mu),[0 0],'r','Linewidth',1.2); % nullcline dx/dt=0
[C2,h2]=contour(X,Y,f2(X,Y,mu),[0 0],'k','Linewidth',1.2); % nullcline dy/dt=0
str=sprintf('mu=%3.3g',mu);
title(str);


